# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_auto_20160520_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['article', 'position', 'published'], 'verbose_name': 'letter', 'verbose_name_plural': 'letters to the editor'},
        ),
    ]
