# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_auto_20160608_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='notes_for_editors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='replace_with_note',
            field=models.BooleanField(default=False, help_text='If checked, then the note to the writer completely overrides the standard response sent to writer.'),
        ),
    ]
