# Generated by Django 2.1.7 on 2019-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_author_commissioned_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='commissioned_staff',
        ),
        migrations.AlterField(
            model_name='author',
            name='freelancer',
            field=models.CharField(choices=[('no', 'No'), ('freelancer', 'Freelancer'), ('commstaff', 'Commissioned staff')], default='no', max_length=10),
        ),
    ]
