# Generated by Django 2.1.7 on 2019-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0006_auto_20190424_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='template_process',
            field=models.BooleanField(default=False),
        ),
    ]
