# Generated by Django 2.1.10 on 2019-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0007_article_template_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_feedback',
            field=models.TextField(blank=True),
        ),
    ]
