# Generated by Django 2.1.12 on 2020-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0009_auto_20190806_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='copyright',
            field=models.TextField(blank=True, default='<p>&copy; 2020 GroundUp.<a rel="license"   href="http://creativecommons.org/licenses/by-nd/4.0/">    <svg viewBox="0 0 100 100"         class="icon icon-creative-commons">        <use xlink:href="#icon-creative-commons">        </use>    </svg></a><br />This article is licensed under a <a rel="license"   href="http://creativecommons.org/licenses/by-nd/4.0/">Creative Commons Attribution-NoDerivatives 4.0 International License</a>.</p><p>You may republish this article, so long as you credit the authors and GroundUp, and do not change the text. Please include a link back to the original article.</p>'),
        ),
    ]
