# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0011_auto_20160515_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='letters_on',
            field=models.BooleanField(default=True),
        ),
    ]
