# Generated by Django 2.2.9 on 2020-05-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0012_auto_20200506_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='facebook_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='facebook_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='facebook_image_caption',
        ),
        migrations.RemoveField(
            model_name='article',
            name='facebook_message',
        ),
        migrations.RemoveField(
            model_name='article',
            name='facebook_send_status',
        ),
        migrations.RemoveField(
            model_name='article',
            name='facebook_wait_time',
        ),
    ]
