# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0013_auto_20160531_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='article',
            name='notified_authors',
            field=models.BooleanField(default=False),
        ),
    ]
