# Generated by Django 2.2.12 on 2020-07-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0014_auto_20200720_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='secret_link',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='secret_link_view',
            field=models.CharField(choices=[('n', 'No prepublication view'), ('r', 'Prepublication view only'), ('o', 'No restrictions')], default='n', max_length=1),
        ),
    ]
