# Generated by Django 3.0.10 on 2021-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0015_auto_20200727_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='copyright',
            field=models.TextField(blank=True, default='<p>&copy; 2021 GroundUp. This article is licensed under a <a rel="license"   href="http://creativecommons.org/licenses/by-nd/4.0/">Creative Commons Attribution-NoDerivatives 4.0 International License</a>.</p><p>You may republish this article, so long as you credit the authors and GroundUp, and do not change the text. Please include a link back to the original article.</p>'),
        ),
    ]
