# Generated by Django 3.0.10 on 2021-03-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0017_auto_20210214_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='invoicing_company',
            field=models.CharField(blank=True, help_text='Leave blank unless you invoice through a company', max_length=100),
        ),
    ]
