# Generated by Django 3.0.10 on 2021-03-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsroom', '0018_author_invoicing_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='freelancer',
            field=models.CharField(choices=[('n', 'No'), ('f', 'Freelancer'), ('c', 'Commissioned staff'), ('t', 'Third party')], default='n', max_length=1),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(default='U', max_length=1)),
                ('text', models.TextField(blank=True)),
                ('notify_republishers', models.BooleanField(default=True, help_text='Only notifies thosethave have already been sent article')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.Article')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
