# Generated by Django 3.0.10 on 2021-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0019_auto_20210319_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='update_type',
            field=models.CharField(choices=[('U', 'Update'), ('I', 'Improvement'), ('C', 'Correction'), ('A', 'Apology'), ('R', 'Retraction')], default='U', max_length=1),
        ),
    ]
