# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0019_auto_20161028_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='donor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='commission',
            name='ledger',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='tax_percent',
            field=models.DecimalField(decimal_places=0, default=25, max_digits=2, verbose_name='tax %'),
        ),
    ]
