# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0020_auto_20161028_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='donor',
            new_name='funder',
        ),
    ]
