# Generated by Django 3.0.10 on 2021-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0021_auto_20210325_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='notify_republishers',
            field=models.BooleanField(default=True, help_text='Only notifies those that have have already been sent article'),
        ),
    ]
