# Generated by Django 3.0.14 on 2021-04-27 06:56

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0022_auto_20210326_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='summary image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='undistracted_layout',
            field=models.BooleanField(default=False, verbose_name='full width layout'),
        ),
    ]
