# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0022_auto_20161029_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
