# Generated by Django 3.2.6 on 2021-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0023_auto_20210427_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='allowance',
            field=models.BooleanField(default=False),
        ),
    ]
