# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0024_auto_20161029_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='id_or_db',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='tax_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
