# Generated by Django 3.2.6 on 2022-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0025_alter_article_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='secret_link',
            field=models.CharField(blank=True, max_length=64, verbose_name='private URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='secret_link_view',
            field=models.CharField(choices=[('n', 'No prepublication view'), ('r', 'Prepublication view only'), ('o', 'No restrictions')], default='n', max_length=1, verbose_name='private URL view'),
        ),
    ]
