# Generated by Django 3.2.6 on 2022-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0026_auto_20220201_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary_image_size',
            field=models.CharField(default='medium', help_text="Choose 'LEAVE' if image size should not be changed.", max_length=20),
        ),
    ]
