# Generated by Django 3.2.6 on 2022-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0027_alter_article_summary_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary_image_size',
            field=models.CharField(default='LEAVE', help_text="Choose 'LEAVE' if image size should not be changed.", max_length=20),
        ),
    ]
