# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0027_auto_20161031_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_tweeted',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='author',
            name='add_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='tax_directive',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
