# Generated by Django 3.2.6 on 2022-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0028_alter_article_summary_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='update_type',
            field=models.CharField(choices=[('U', 'Update'), ('I', 'Improvement'), ('C', 'Correction'), ('A', 'Apology'), ('R', 'Retraction')], default='C', max_length=1),
        ),
    ]
