# Generated by Django 3.2.6 on 2022-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0029_alter_correction_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='notify_republishers',
            field=models.BooleanField(default=False, help_text='Only notifies those that have have already been sent article'),
        ),
    ]
