# Generated by Django 3.2.6 on 2022-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0030_alter_correction_notify_republishers'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='publishers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
