# Generated by Django 3.2.15 on 2022-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0032_auto_20220703_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='secret_link_view',
            field=models.CharField(choices=[('n', 'No prepublication view'), ('r', 'Prepublication view only'), ('o', 'No restrictions')], default='r', max_length=1, verbose_name='private URL view'),
        ),
    ]
