# Generated by Django 3.2.15 on 2023-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0035_auto_20230302_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_publish',
            field=models.BooleanField(default=False),
        ),
    ]
