# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0036_auto_20161105_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=0, default=0, help_text='If you are VAT regisered set this to 14 else leave at 0', max_digits=2, verbose_name='vat %'),
        ),
    ]
