# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0037_invoice_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='add_vat',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id_or_db',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tax_directive',
        ),
        migrations.AddField(
            model_name='author',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='bank_account_type',
            field=models.CharField(default='CURRENT', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='bank_branch_code',
            field=models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='bank_branch_name',
            field=models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='bank_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateField(blank=True, help_text='Please fill this in. Required by SARS.', null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='author',
            name='iban',
            field=models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=34),
        ),
        migrations.AddField(
            model_name='author',
            name='identification',
            field=models.CharField(blank=True, help_text='SA ID, passport or some form of official identification', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=12),
        ),
        migrations.AddField(
            model_name='author',
            name='tax_percent',
            field=models.DecimalField(decimal_places=0, default=25, help_text='Unless you have a tax directive we have to deduct 25% PAYE for SARS.', max_digits=2, verbose_name='tax %'),
        ),
        migrations.AddField(
            model_name='author',
            name='vat',
            field=models.DecimalField(decimal_places=0, default=0, help_text='If you are VAT regisered set this to 14 else leave at 0', max_digits=2, verbose_name='vat %'),
        ),
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.TextField(blank=True, help_text='Please fill this in. Required by SARS.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='tax_no',
            field=models.CharField(blank=True, help_text='Necessary for SARS.', max_length=50),
        ),
    ]
