# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0038_auto_20161106_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('0', 'Unpaid'), ('1', 'Queried by reporter-unpaid'), ('2', 'Approved by reporter-unpaid'), ('3', 'Approved by editor-unpaid'), ('4', 'Paid')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_no',
            field=models.CharField(blank=True, help_text='Necessary for SARS.', max_length=50, verbose_name='tax number'),
        ),
    ]
