# Generated by Django 4.2.18 on 2025-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0038_alter_article_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='display_at_top',
            field=models.BooleanField(default=False, help_text='If checked, this correction will be displayed at the top of the article instead of at the bottom.'),
        ),
    ]
