# Generated by Django 4.2.18 on 2025-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0039_correction_display_at_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bonus_off',
            field=models.BooleanField(default=False, verbose_name='Turn off bonus'),
        ),
    ]
