# Generated by Django 4.2.18 on 2025-06-30 21:01

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('newsroom', '0039_correction_display_at_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageImage',
            fields=[
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='flatpages.flatpage')),
                ('header_image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Header Image')),
            ],
        ),
    ]
