# Generated by Django 4.2.18 on 2025-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0039_correction_display_at_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('intern', 'Intern'), ('standard', 'Standard'), ('senior', 'Senior'), ('experienced', 'Experienced'), ('exceptional', 'Exceptional'), ('exceptional_plus', 'Exceptional Plus')], default='standard', max_length=20),
        ),
    ]
