# Generated by Django 4.2.22 on 2025-07-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0040_alter_author_level'),
        ('newsroom', '0040_flatpageimage'),
    ]

    operations = [
    ]
