# Generated by Django 4.2.22 on 2025-07-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0040_author_bonus_off'),
        ('newsroom', '0041_merge_0040_alter_author_level_0040_flatpageimage'),
    ]

    operations = [
    ]
