# Generated by Django 4.2.18 on 2025-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0042_merge_20250704_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpageimage',
            options={'verbose_name': 'Header Image'},
        ),
        migrations.AddField(
            model_name='correction',
            name='use_html',
            field=models.BooleanField(default=False, help_text='If checked, the text will be rendered as HTML. Otherwise, line breaks will be preserved as paragraphs.'),
        ),
    ]
