# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0042_auto_20161106_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['status', '-modified']},
        ),
    ]
