# Generated by Django 4.2.18 on 2025-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0043_alter_flatpageimage_options_correction_use_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, help_text="If this is not blank it overrides the value of the author fields. If 'Custom' style is selected, use {author_01}, {author_02} etc. as placeholders.", max_length=200, verbose_name='customised byline'),
        ),
        migrations.AlterField(
            model_name='article',
            name='byline_style',
            field=models.CharField(choices=[('ST', 'Standard'), ('TP', 'Text By [First Author] Photos By [Second Author]'), ('CU', 'Custom')], default='ST', max_length=2),
        ),
    ]
