# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0043_auto_20161107_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='author',
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
