# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0044_auto_20161107_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notified_authors',
            field=models.BooleanField(default=False),
        ),
    ]
