# Generated by Django 4.2.18 on 2026-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0045_alter_article_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostDeeplyRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_list', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'most deeply read',
            },
        ),
    ]
