# Generated by Django 4.2.27 on 2026-03-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencing', '0002_licensee_contract_licensee_unique_licensee_and_more'),
        ('newsroom', '0046_mostdeeplyread'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licencing.licence'),
        ),
    ]
