# Generated by Django 4.2.29 on 2026-03-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0047_article_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='copyright',
            field=models.TextField(blank=True, default="<p>&copy; 2026 GroundUp. This article is licensed under the <a href='https://groundup.org.za/licencing/detail/2/'>GroundUp Republication Licence Version 1.0</a>. Email <a href='mailto:info@groundup.org.za'>info@groundup.org.za</a> to request permission to republish.</p>"),
        ),
    ]
