# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0050_auto_20170116_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredit',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
