# Generated by Django 5.2 on 2026-04-25 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0050_migrate_2fa_to_allauth_mfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='useredit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_names', 'last_name'), name='unique_first_names_last_name'),
        ),
        migrations.AddConstraint(
            model_name='useredit',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_article_user'),
        ),
    ]
