# Generated by Django 5.2.13 on 2026-08-18 15:42

import django.core.validators
import django.db.models.deletion
import filebrowser.fields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0051_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text="Singular label shown on a video card, e.g. 'Explainer' where the category is 'Explainers'. Defaults to the name.", max_length=100)),
                ('introduction', models.TextField(blank=True, help_text='Use unfiltered HTML.')),
                ('position', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers sort first in the filter bar.')),
            ],
            options={
                'verbose_name': 'video category',
                'verbose_name_plural': 'video categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('youtube_id', models.CharField(help_text='Paste the YouTube URL or Short URL. Only the video id is kept. Long enough to hold a pasted URL before it is reduced to the id.', max_length=200, verbose_name='YouTube video')),
                ('video_format', models.CharField(choices=[('L', 'Landscape (standard YouTube video)'), ('S', 'Vertical (YouTube Short)')], default='L', help_text='Verticals are shown in the Shorts rail rather than the main grid.', max_length=1)),
                ('summary', models.TextField(blank=True, help_text='One or two sentences. Used on the videos page, the home page and as the search description.')),
                ('body', models.TextField(blank=True, help_text='Optional article-style text published below the video. Use unfiltered HTML.')),
                ('duration', models.CharField(blank=True, help_text='Length as m:ss or h:mm:ss, e.g. 9:42.', max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^(?:(?P<h>\\d+):)?(?P<m>\\d{1,2}):(?P<s>\\d{2})$'), 'Use m:ss or h:mm:ss, e.g. 9:42.')], verbose_name='length (m:ss)')),
                ('byline', models.CharField(blank=True, help_text="If this is not blank it overrides the author field, e.g. 'GroundUp Video Team'.", max_length=200, verbose_name='customised byline')),
                ('credits', models.TextField(blank=True, help_text='Production credits shown in the grey strip under the video.')),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, help_text='Only needed to override the thumbnail YouTube generates.', max_length=200, verbose_name='thumbnail')),
                ('thumbnail_alt', models.CharField(blank=True, help_text='Description of the thumbnail for assistive technology.', max_length=200)),
                ('published', models.DateTimeField(blank=True, help_text='Leave blank to keep the video off the site. A future date publishes it then.', null=True)),
                ('promote', models.BooleanField(default=False, help_text='Pin this video to the top of the videos page instead of the newest.')),
                ('include_on_home', models.BooleanField(default=True)),
                ('transcript_on_request', models.BooleanField(default=True, help_text='Show the note offering a transcript and Creative Commons republication.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='newsroom.author')),
                ('related_articles', models.ManyToManyField(blank=True, help_text='Articles to offer alongside this video.', related_name='videos', to='newsroom.article')),
                ('topics', models.ManyToManyField(blank=True, related_name='videos', to='newsroom.topic')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='newsroom.videocategory')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='VideoChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecode', models.CharField(help_text='m:ss, e.g. 2:41.', max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^(?:(?P<h>\\d+):)?(?P<m>\\d{1,2}):(?P<s>\\d{2})$'), 'Use m:ss or h:mm:ss, e.g. 9:42.')], verbose_name='time (m:ss)')),
                ('description', models.CharField(max_length=250)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='newsroom.video')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-published', 'video_format'], name='newsroom_vi_publish_d0b1f8_idx'),
        ),
    ]
