# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0053_auto_20170214_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
