# Generated by Django 5.2.13 on 2026-08-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0053_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='copyright',
            field=models.TextField(blank=True, default="<p>&copy; 2026 GroundUp. This video is <b>not</b> available under a Creative Commons licence. It may be republished under the <a href='https://groundup.org.za/licencing/detail/2/'>GroundUp Republication Licence Version 1.0</a>. Email <a href='mailto:info@groundup.org.za'>info@groundup.org.za</a> to request permission to republish.</p>", help_text='Shown at the foot of the video page. GroundUp videos are not published under Creative Commons, so this is where the Republication Licence is stated. Use unfiltered HTML.', verbose_name='copyright and licence'),
        ),
        migrations.AlterField(
            model_name='video',
            name='credits',
            field=models.TextField(blank=True, help_text='A note shown in the strip under the video, e.g. where and when it was filmed. Who worked on it goes in Contributors, below.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='transcript_on_request',
            field=models.BooleanField(default=True, help_text='Show the note offering a transcript of the video.'),
        ),
        migrations.CreateModel(
            name='VideoContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reporting', 'Reporting'), ('producing', 'Producing'), ('presenting', 'Presenting'), ('script', 'Script'), ('camera', 'Camera'), ('sound', 'Sound'), ('editing', 'Video editing'), ('animation', 'Animation and graphics'), ('photographs', 'Photographs'), ('translation', 'Translation'), ('subtitles', 'Subtitles'), ('factcheck', 'Fact checking'), ('other', 'Other')], default='reporting', max_length=20)),
                ('note', models.CharField(blank=True, help_text="Optional detail shown in brackets after the name, e.g. 'second camera'.", max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers are credited first within a role.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contributions', to='newsroom.author')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='newsroom.video')),
            ],
            options={
                'verbose_name': 'video contributor',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('video', 'author', 'role'), name='unique_video_contributor_role')],
            },
        ),
    ]
