# Generated by Django 5.2.13 on 2026-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0054_video_copyright_alter_video_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontributor',
            name='no_payment',
            field=models.BooleanField(default=False, help_text='Tick where this person is not to be paid for the video, for example staff on a salary or a contribution given for free. Publishing the video raises a payment item for everyone else.', verbose_name='do not pay'),
        ),
    ]
