# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 10:21
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


def set_blank(apps, schema_editor):
    Article = apps.get_model('newsroom', 'Article')
    for article in Article.objects.all():
        save = False
        if article.facebook_image is None:
            article.facebook_image = ""
            save = True
        if article.primary_image is None:
            article.primary_image = ""
            save = True
        if article.summary_image is None:
            article.summary_image = ""
            save = True
        if save is True:
            article.save()
    Author = apps.get_model('newsroom', 'Author')
    for author in Author.objects.all():
        if author.photo is None:
            author.photo = ""
            author.save()
    Topic = apps.get_model('newsroom', 'Topic')
    for topic in Topic.objects.all():
        if topic.icon is None:
            topic.icon = ""
            topic.save()

class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0054_auto_20170227_1605'),
    ]

    operations = [
        migrations.RunPython(set_blank),
        migrations.AlterField(
            model_name='article',
            name='facebook_image',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', help_text='Leave blank to use primary image.', max_length=200, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='primary_image',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='summary_image',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
