# Generated by Django 5.2.13 on 2026-09-22 08:46

from django.db import migrations, models


ROLE_ORDER = [
    "reporting",
    "producing",
    "presenting",
    "script",
    "story_editing",
    "camera",
    "sound",
    "editing",
    "animation",
    "photographs",
    "translation",
    "subtitles",
    "factcheck",
    "other",
]


def copy_authors(apps, schema_editor):
    Video = apps.get_model("newsroom", "Video")
    for video in Video.objects.exclude(author__isnull=True):
        video.authors.add(video.author)


def uncopy_authors(apps, schema_editor):
    Video = apps.get_model("newsroom", "Video")
    for video in Video.objects.all():
        first = video.authors.first()
        if first:
            video.author = first
            video.save(update_fields=["author"])


def merge_roles(apps, schema_editor):
    VideoContributor = apps.get_model("newsroom", "VideoContributor")
    kept = {}
    for contributor in VideoContributor.objects.order_by("position", "id"):
        key = (contributor.video_id, contributor.author_id)
        first = kept.get(key)
        if first is None:
            contributor.roles = contributor.role
            contributor.save(update_fields=["roles"])
            kept[key] = contributor
            continue
        roles = [role for role in first.roles.split(",") if role]
        if contributor.role not in roles:
            roles.append(contributor.role)
        first.roles = ",".join(
            sorted(set(roles), key=lambda role: ROLE_ORDER.index(role)
                   if role in ROLE_ORDER else len(ROLE_ORDER))
        )
        first.no_payment = first.no_payment and contributor.no_payment
        if contributor.note and contributor.note not in first.note:
            first.note = ", ".join(
                part for part in [first.note, contributor.note] if part
            )[:100]
        first.save(update_fields=["roles", "no_payment", "note"])
        contributor.delete()


def split_roles_back(apps, schema_editor):
    VideoContributor = apps.get_model("newsroom", "VideoContributor")
    for contributor in VideoContributor.objects.all():
        roles = [role for role in contributor.roles.split(",") if role]
        contributor.role = roles[0] if roles else "reporting"
        contributor.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0055_videocontributor_no_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who the video is bylined to. Leave blank and the "
                "byline falls back to whoever is credited with reporting, and "
                "then to 'GroundUp Video Team'.",
                related_name="videos_new",
                to="newsroom.author",
            ),
        ),
        migrations.AddField(
            model_name="videocontributor",
            name="roles",
            field=models.CharField(
                default="reporting",
                help_text="Everything this person did on the video. They are "
                "credited under each of them.",
                max_length=200,
                verbose_name="what they did",
            ),
        ),
        migrations.RunPython(copy_authors, uncopy_authors),
        migrations.RunPython(merge_roles, split_roles_back),
        migrations.RemoveConstraint(
            model_name="videocontributor",
            name="unique_video_contributor_role",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="newsroom_vi_publish_d0b1f8_idx",
        ),
        migrations.RemoveField(
            model_name="video",
            name="author",
        ),
        migrations.RemoveField(
            model_name="video",
            name="transcript_on_request",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_format",
        ),
        migrations.RemoveField(
            model_name="videocontributor",
            name="role",
        ),
        migrations.AlterField(
            model_name="video",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who the video is bylined to. Leave blank and the "
                "byline falls back to whoever is credited with reporting, and "
                "then to 'GroundUp Video Team'.",
                related_name="videos",
                to="newsroom.author",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="byline",
            field=models.CharField(
                blank=True,
                help_text="If this is not blank it overrides the authors "
                "field, e.g. 'GroundUp Video Team'.",
                max_length=200,
                verbose_name="customised byline",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["-published"], name="newsroom_vi_publish_c45b40_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="videocontributor",
            constraint=models.UniqueConstraint(
                fields=("video", "author"), name="unique_video_contributor"
            ),
        ),
    ]
