# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0056_article_byline_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline_style',
            field=models.CharField(choices=[('ST', 'Standard'), ('TP', 'Text By [First Author] Photos By [Second Author]')], default='ST', max_length=2),
        ),
    ]
