# Generated by Django 5.2.13 on 2026-09-22 08:46

from django.db import migrations


CATEGORIES = [
    ("explainer", "Explainer", "Explainer", 10),
    ("news-reel", "News reel", "News reel", 20),
    ("roundup", "Roundup", "Roundup", 30),
    ("feature", "Feature", "Feature", 40),
]

RENAMES = [
    ("explainers", "explainer"),
    ("documentaries", "feature"),
    ("features", "feature"),
]

OLD_CATEGORIES = [
    ("Explainers", "explainers", "Explainer", 10),
    ("Investigations", "investigations", "Investigation", 20),
    ("Documentaries", "documentaries", "Documentary", 30),
    ("Court cases", "court-cases", "Court case", 40),
    ("Features", "features", "Feature", 50),
]


def rework(apps, schema_editor):
    VideoCategory = apps.get_model("newsroom", "VideoCategory")
    Video = apps.get_model("newsroom", "Video")

    for old_slug, new_slug in RENAMES:
        name, label, position = next(
            (n, l, p) for s, n, l, p in CATEGORIES if s == new_slug
        )
        old = VideoCategory.objects.filter(slug=old_slug).first()
        if old is None:
            continue
        existing = VideoCategory.objects.filter(slug=new_slug).exclude(
            pk=old.pk).first()
        if existing:
            Video.objects.filter(category=old).update(category=existing)
            old.delete()
            continue
        old.slug = new_slug
        old.name = name
        old.label = label
        old.position = position
        old.save()

    for slug, name, label, position in CATEGORIES:
        VideoCategory.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "label": label, "position": position},
        )

    VideoCategory.objects.exclude(
        slug__in=[slug for slug, _, _, _ in CATEGORIES]
    ).filter(slug__in=[slug for _, slug, _, _ in OLD_CATEGORIES]).delete()


def unrework(apps, schema_editor):
    VideoCategory = apps.get_model("newsroom", "VideoCategory")
    for name, slug, label, position in OLD_CATEGORIES:
        VideoCategory.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "label": label, "position": position},
        )
    VideoCategory.objects.filter(
        slug__in=[slug for slug, _, _, _ in CATEGORIES]
    ).exclude(slug__in=[slug for _, slug, _, _ in OLD_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("newsroom", "0056_video_landscape_only_and_multi_role_credits"),
    ]

    operations = [
        migrations.RunPython(rework, unrework),
    ]
