# Generated by Django 5.2.13 on 2026-09-23 08:25

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0057_video_categories_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='copyright',
            field=models.TextField(blank=True, default="<p>&copy; 2026 GroundUp. This video is <b>not</b> available under a Creative Commons licence. It may be republished under the <a href='https://groundup.org.za/licencing/detail/2/'>GroundUp Republication Licence Version 1.0</a>. Email <a href='mailto:info@groundup.org.za'>info@groundup.org.za</a> to request permission to republish.</p>", help_text='Shown at the foot of the video page. Use unfiltered HTML.', verbose_name='copyright and licence'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='Length as m:ss or h:mm:ss, e.g. 9:42.', max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^(?:(?P<h>\\d+):)?(?P<m>\\d{1,2}):(?P<s>[0-5]\\d)$'), 'Use m:ss or h:mm:ss, e.g. 9:42.')], verbose_name='length (m:ss)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.DateTimeField(blank=True, help_text='Leave blank to keep the video off the site', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, help_text='One or 2 sentences. Used on the videos page, the home page and as the search description.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_alt',
            field=models.CharField(blank=True, help_text='Description of the thumbnail for alttext', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='Paste the YouTube URL. Only the video id is kept.', max_length=200, verbose_name='YouTube video'),
        ),
        migrations.AlterField(
            model_name='videochapter',
            name='timecode',
            field=models.CharField(help_text='m:ss, e.g. 2:41.', max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^(?:(?P<h>\\d+):)?(?P<m>\\d{1,2}):(?P<s>[0-5]\\d)$'), 'Use m:ss or h:mm:ss, e.g. 9:42.')], verbose_name='time (m:ss)'),
        ),
        migrations.AlterField(
            model_name='videocontributor',
            name='no_payment',
            field=models.BooleanField(default=False, help_text='Tick if this person is not to be paid for the video. Publishing the video raises a payment item for everyone else.', verbose_name='do not pay'),
        ),
    ]
