# Generated by Django 5.2.13 on 2026-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0058_video_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pin_to_home',
            field=models.BooleanField(default=False, help_text='Show this video above everything else on the home page. Pinning it unpins any other video. It only appears once published.', verbose_name='pin to top of home page'),
        ),
    ]
