# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0059_auto_20171011_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='oldest_first',
            field=models.BooleanField(default=False),
        ),
    ]
