# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0060_topic_oldest_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='oldest_first',
        ),
        migrations.AddField(
            model_name='topic',
            name='newest_first',
            field=models.BooleanField(default=True),
        ),
    ]
