# Generated by Django 2.1.12 on 2020-01-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='characters_left',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
