# Generated by Django 3.2.6 on 2022-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20200114_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='wait_time',
            field=models.PositiveIntegerField(default=0, help_text='Number of minutes after publication till tweet.'),
        ),
    ]
