# Generated by Django 3.2.15 on 2023-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('case_name', models.CharField(blank=True, help_text='E.g. Jane Doe and Others v Joe Bloggs and Other', max_length=100)),
                ('accept_case_name', models.BooleanField(default=False)),
                ('judges', models.TextField(blank=True, help_text='Enter first and surnames of judges separated by comma.\nPlease enter at least one judge.', max_length=1000)),
                ('accept_judges', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('R', 'Judgment reserved'), ('H', 'Judgment handed down'), ('S', 'Case settled'), ('O', 'Other')], max_length=3)),
                ('accept_event_type', models.BooleanField(default=False)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('accept_event_date', models.BooleanField(default=False)),
                ('document_url', models.URLField(blank=True, help_text='URL of document that may assist verification.')),
                ('accept_document_url', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, help_text='Document that may assist verification (maximum 10MB)', null=True, upload_to='')),
                ('notes', models.TextField(blank=True, help_text='Please provide further information to assist us', max_length=2000)),
                ('accept_notes', models.BooleanField(default=False)),
                ('email_address', models.EmailField(help_text='We may need to contact you but we will not share\nyour email address with anyone else.', max_length=254)),
                ('unique_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
