# Generated by Django 3.2.15 on 2023-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='event',
            name='process_status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('I', 'Ignore'), ('P', 'Processed')], default='U', max_length=2),
        ),
    ]
