# Generated by Django 3.2.15 on 2023-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0003_auto_20230531_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='case_number',
            field=models.CharField(help_text='Please enter a valid South African court case number.', max_length=20),
        ),
    ]
