# Generated by Django 3.2.15 on 2023-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_alter_event_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['case_number', '-modified']},
        ),
        migrations.AlterField(
            model_name='event',
            name='case_number',
            field=models.CharField(help_text='Enter a valid South African court case number.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_address',
            field=models.EmailField(help_text='We may need to contact you but we will not share your email address with anyone else.', max_length=254, verbose_name='Your email address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, help_text="Please give the exact date. If you're not certain, please indicate in the notes below.", null=True, verbose_name='Date it happened'),
        ),
        migrations.AlterField(
            model_name='event',
            name='judges',
            field=models.TextField(blank=True, help_text='Enter first and surnames of judges, one per line. Please enter at least one judge.', max_length=1000, verbose_name='Judge(s)'),
        ),
    ]
