# Generated by Django 3.2.15 on 2023-06-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0005_auto_20230602_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='court',
            field=models.ForeignKey(default=1, help_text='Select the court where this case was heard.', on_delete=django.db.models.deletion.CASCADE, to='judgment.court'),
        ),
    ]
