# Generated by Django 3.2.15 on 2023-06-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0006_auto_20230602_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='court',
            field=models.ForeignKey(help_text='Select the court where this case was heard.', null=True, on_delete=django.db.models.deletion.CASCADE, to='judgment.court'),
        ),
    ]
