# Generated by Django 3.2.15 on 2023-06-06 17:57

from django.db import migrations, models
import judgment.models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0008_alter_event_court'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['case_id', '-modified']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='case_number',
        ),
        migrations.AddField(
            model_name='event',
            name='case_id',
            field=models.CharField(default='123/456', help_text='Enter a valid South African court case id.', max_length=20, validators=[judgment.models.validate_case]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('R', 'Judgment reserved'), ('H', 'Judgment handed down'), ('I', 'Judge died or incapacitated'), ('S', 'Case settled'), ('O', 'Other')], help_text='Indicate if judgment was reserved, handed down or something else happened.', max_length=3, verbose_name='What happened'),
        ),
    ]
