# Generated by Django 3.2.15 on 2023-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0009_auto_20230606_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='case_name',
            field=models.CharField(blank=True, help_text='E.g. Jane Doe and Others v Joe Bloggs and Other', max_length=200),
        ),
    ]
