# Generated by Django 3.2.15 on 2023-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0010_alter_event_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='judges',
            field=models.TextField(blank=True, help_text='Enter one judge per line. Surname followed by AJ, J or JP (no comma between surname and title). Please enter at least one judge.', max_length=1000, verbose_name='Judge(s)'),
        ),
    ]
