# Generated by Django 4.2.18 on 2025-12-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0044_alter_article_byline_alter_article_byline_style'),
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('standard', 'Standard HTML'), ('topic', 'Topic'), ('category', 'Category')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='num_articles',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='selected_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsroom.category'),
        ),
        migrations.AddField(
            model_name='block',
            name='selected_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsroom.topic'),
        ),
    ]
