# Generated by Django 4.2.18 on 2025-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_block_block_type_block_num_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='feature_first_article',
            field=models.BooleanField(default=True, help_text='If checked, the first article will be styled as a featured article.'),
        ),
    ]
