# Generated by Django 4.2.18 on 2025-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_block_feature_first_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_summary_featured',
            field=models.BooleanField(default=True, verbose_name='Show summary for featured article'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_summary_standard',
            field=models.BooleanField(default=True, verbose_name='Show summary for standard articles'),
        ),
    ]
