# Generated by Django 4.2.18 on 2026-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_block_show_summary_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Override the default title', max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('standard', 'Standard HTML'), ('topic', 'Topic'), ('category', 'Category'), ('chart_of_the_week', 'Chart of the Week')], default='standard', max_length=20),
        ),
    ]
