# Generated by Django 4.2.18 on 2026-01-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_block_custom_title_alter_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_title_featured',
            field=models.BooleanField(default=True, verbose_name='Show title for featured article'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_title_standard',
            field=models.BooleanField(default=True, verbose_name='Show title for standard articles'),
        ),
    ]
