# Generated by Django 4.2.18 on 2026-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_block_show_title_featured_block_show_title_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('standard', 'Standard HTML'), ('topic', 'Topic'), ('category', 'Category'), ('chart_of_the_week', 'Chart of the Week'), ('creative_commons_gallery', 'Creative Commons Gallery')], default='standard', max_length=50),
        ),
    ]
