# Generated by Django 4.2.18 on 2026-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_alter_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_byline_featured',
            field=models.BooleanField(default=True, verbose_name='Show byline for featured article'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_byline_standard',
            field=models.BooleanField(default=True, verbose_name='Show byline for standard articles'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_category_featured',
            field=models.BooleanField(default=True, verbose_name='Show category for featured article'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_category_standard',
            field=models.BooleanField(default=True, verbose_name='Show category for standard articles'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_date_featured',
            field=models.BooleanField(default=True, verbose_name='Show date for featured article'),
        ),
        migrations.AddField(
            model_name='block',
            name='show_date_standard',
            field=models.BooleanField(default=True, verbose_name='Show date for standard articles'),
        ),
    ]
