# Generated by Django 4.2.18 on 2026-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_block_show_byline_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='exclude_duplicates',
            field=models.BooleanField(default=False, help_text='If checked, articles already displayed on the page will be excluded.', verbose_name='Exclude duplicates'),
        ),
    ]
