# Generated by Django 4.2.29 on 2026-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_block_exclude_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='display_in_columns',
            field=models.BooleanField(default=False, help_text='If checked, standard articles will be displayed in a two-column grid.', verbose_name='Display standard articles in columns'),
        ),
    ]
