# Generated by Django 5.2.16 on 2026-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_block_display_in_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('standard', 'Standard HTML'), ('topic', 'Topic'), ('videos', 'Videos'), ('category', 'Category'), ('chart_of_the_week', 'Chart of the Week'), ('creative_commons_gallery', 'Creative Commons Gallery')], default='standard', max_length=50),
        ),
    ]
