# Generated by Django 5.2.16 on 2026-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_alter_block_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='video_categories',
            field=models.BooleanField(default=True, verbose_name='Show categories'),
        ),
        migrations.AddField(
            model_name='block',
            name='video_dates',
            field=models.BooleanField(default=False, verbose_name='Show dates'),
        ),
        migrations.AddField(
            model_name='block',
            name='video_durations',
            field=models.BooleanField(default=True, verbose_name='Show durations'),
        ),
        migrations.AddField(
            model_name='block',
            name='video_featured',
            field=models.BooleanField(default=False, verbose_name='Feature first video'),
        ),
        migrations.AddField(
            model_name='block',
            name='video_summaries',
            field=models.BooleanField(default=False, verbose_name='Show summaries'),
        ),
    ]
