# Generated by Django 2.1.12 on 2019-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='republisher',
            name='ask_for_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='republisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
