# Generated by Django 3.2.6 on 2022-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republisher', '0002_auto_20190928_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='republisherarticle',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
