# Generated by Django 4.2.29 on 2026-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('republisher', '0004_republisher_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='republisher',
            name='ask_for_analytics',
            field=models.BooleanField(default=True),
        ),
    ]
