# Generated by Django 5.2 on 2026-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0051_alter_author_unique_together_and_more'),
        ('republisher', '0005_alter_republisher_ask_for_analytics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='republisherarticle',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='republisherarticle',
            constraint=models.UniqueConstraint(fields=('article', 'republisher'), name='unique_article_republisher'),
        ),
    ]
