# Generated by Django 2.1.4 on 2018-12-10 16:17

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, choices=[('', ''), ('Article author', 'Article author'), ('Photographs', 'Photographs'), ('Article cancellation fee', 'Article cancellation fee'), ('Expenses', 'Expenses'), ('Editing', 'Editing'), ('Subediting', 'Subediting'), ('Consulting', 'Consulting'), ('Administration', 'Administration'), ('Sundry', 'Sundry')], default='Article author', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('sys_generated', models.BooleanField(default=False)),
                ('date_generated', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_notified_approved', models.DateTimeField(blank=True, null=True)),
                ('commission_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='amount')),
                ('taxable', models.BooleanField(default=True)),
                ('vatable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Article')),
            ],
            options={
                'ordering': ['invoice', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField(default=0)),
                ('identification', models.CharField(blank=True, help_text='SA ID, passport or some form of official identification', max_length=20)),
                ('dob', models.DateField(blank=True, help_text='Required by SARS', null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, help_text='Required by SARS')),
                ('bank_name', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, verbose_name='account')),
                ('bank_account_type', models.CharField(default='CURRENT', max_length=20, verbose_name='account type')),
                ('bank_branch_name', models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20, verbose_name='branch name')),
                ('bank_branch_code', models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20, verbose_name='branch code')),
                ('swift_code', models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=12)),
                ('iban', models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=34)),
                ('tax_no', models.CharField(blank=True, help_text='Necessary for SARS.', max_length=50, verbose_name='tax number')),
                ('tax_percent', models.DecimalField(decimal_places=0, default=25, help_text='Unless you have a tax directive we have to deduct 25% PAYE', max_digits=2, verbose_name='PAYE %')),
                ('vat', models.DecimalField(decimal_places=0, default=0, help_text='If you are VAT registered set this to 15 else leave at 0', max_digits=2, verbose_name='VAT %')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='amount')),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vat_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('invoice', filebrowser.fields.FileBrowseField(blank=True, max_length=200)),
                ('proof', filebrowser.fields.FileBrowseField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('-', 'Invoice being prepared by editor'), ('0', 'Reporter needs to approve'), ('1', 'Queried by reporter'), ('2', 'Approved by reporter'), ('3', 'Approved by editor'), ('4', 'Paid'), ('5', 'Deleted')], default='-', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('query', models.TextField(blank=True, help_text='Explain your query here if you have one', max_length=3000)),
                ('date_time_reporter_approved', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_time_editor_approved', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_time_processed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_notified_payment', models.DateTimeField(blank=True, editable=False, null=True)),
                ('our_reference', models.CharField(blank=True, max_length=20)),
                ('their_reference', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author')),
            ],
            options={
                'ordering': ['status', '-modified'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Selecting a fund approves the commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Fund'),
        ),
        migrations.AddField(
            model_name='commission',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('author', 'invoice_num')},
        ),
    ]
