# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['invoice', 'created']},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='author',
        ),
        migrations.AlterField(
            model_name='commission',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('author', 'invoice_num')]),
        ),
    ]
