# Generated by Django 2.1.7 on 2019-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='level',
            field=models.CharField(choices=[('intern', 'Intern'), ('standard', 'Standard'), ('senior', 'Senior'), ('experienced', 'Experienced'), ('exceptional', 'Exceptional')], default='standard', max_length=15),
        ),
    ]
