# Generated by Django 2.1.7 on 2019-03-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoice_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, choices=[('', ''), ('Administration', 'Administration'), ('Article author', 'Article author'), ('Article cancellation fee', 'Article cancellation fee'), ('Consulting', 'Consulting'), ('Expenses', 'Expenses'), ('Editing', 'Editing'), ('Fact check', 'Fact check'), ('Photographs', 'Photographs'), ('Subediting', 'Subediting'), ('Sundry', 'Sundry')], default='Article author', max_length=50),
        ),
    ]
