# Generated by Django 2.1.7 on 2019-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190320_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='vatable',
            field=models.BooleanField(default=True),
        ),
    ]
