# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20161108_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_account_type',
            field=models.CharField(default='CURRENT', max_length=20, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_branch_code',
            field=models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20, verbose_name='branch code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_branch_name',
            field=models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20, verbose_name='branch name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='query',
            field=models.TextField(blank=True, help_text='Explain your query here if you have one', max_length=3000),
        ),
    ]
