# Generated by Django 3.0.10 on 2021-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190530_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('primary_photo', models.FloatField(default=0.0)),
                ('inside_photo', models.FloatField(default=0.0)),
                ('opinion', models.FloatField(default=0.0)),
                ('brief', models.FloatField(default=0.0)),
                ('law', models.FloatField(default=0.0)),
                ('news', models.FloatField(default=0.0)),
                ('video', models.FloatField(default=0.0)),
                ('science', models.FloatField(default=0.0)),
                ('simple_feature', models.FloatField(default=0.0)),
                ('complex_feature', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
                ('bonus_article', models.PositiveSmallIntegerField(default=4)),
                ('level_intern', models.FloatField(default=0.5)),
                ('level_standard', models.FloatField(default=1.0)),
                ('level_senior', models.FloatField(default=1.35)),
                ('level_experienced', models.FloatField(default=1.7)),
                ('level_exceptional', models.FloatField(default=2.2)),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
    ]
