# Generated by Django 3.0.10 on 2021-02-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates',
            new_name='RateCard',
        ),
    ]
