# Generated by Django 3.0.10 on 2021-03-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210311_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='fund',
            new_name='funder',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='ledger',
        ),
        migrations.AddField(
            model_name='fund',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commission',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Selecting a Pastel ledger account approves the commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Fund', verbose_name='ledger'),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
