# Generated by Django 3.0.10 on 2021-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20210311_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='funder',
            new_name='fund',
        ),
    ]
