# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20161116_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
