# Generated by Django 3.0.10 on 2021-03-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20210311_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='funder',
            field=models.BooleanField(default=True),
        ),
    ]
