# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20170125_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, choices=[('', ''), ('Article author', 'Article author'), ('Photographs', 'Photographs'), ('Article cancellation fee', 'Article cancellation fee'), ('Expenses', 'Expenses'), ('Editing', 'Editing'), ('Subediting', 'Subediting'), ('Consulting', 'Consulting'), ('Administration', 'Administration'), ('Sundry', 'Sundry')], default='Article author', max_length=50),
        ),
    ]
