# Generated by Django 3.0.10 on 2021-03-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_fund_funder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='funder',
            new_name='account',
        ),
    ]
