# Generated by Django 3.0.10 on 2021-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20210311_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
