# Generated by Django 3.0.10 on 2021-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_fund_deprecated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='account',
        ),
        migrations.AddField(
            model_name='fund',
            name='ledger',
            field=models.BooleanField(default=False),
        ),
    ]
