# Generated by Django 3.0.10 on 2021-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20210311_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='latest_payment_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='order_form_attached',
        ),
        migrations.AddField(
            model_name='invoice',
            name='requisition_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
