# Generated by Django 3.0.10 on 2021-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_auto_20210312_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoicing_company',
            field=models.CharField(blank=True, help_text='Leave blank unless you invoice through a company', max_length=100),
        ),
    ]
