# Generated by Django 3.0.10 on 2021-03-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_invoice_invoicing_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='merge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_this', to='payment.Invoice'),
        ),
    ]
