# Generated by Django 3.0.10 on 2021-03-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_invoice_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='merge',
        ),
    ]
