# Generated by Django 3.0.10 on 2021-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_invoice_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='next_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fund',
            name='prefix',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='requisition',
            field=models.BooleanField(default=False),
        ),
    ]
