# Generated by Django 3.0.10 on 2021-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20210315_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_emails',
            field=models.CharField(blank=True, help_text='Additional emails to notify separated by commas', max_length=200),
        ),
    ]
