# Generated by Django 3.0.10 on 2021-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20210323_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='ledger',
            field=models.BooleanField(default=False, verbose_name='pastel'),
        ),
    ]
