# Generated by Django 3.0.10 on 2021-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20210325_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Leave at 0 for system to calculate.', max_digits=8),
        ),
    ]
