# Generated by Django 3.0.14 on 2021-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_payerequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_due',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='vat_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Leave at 0 for system to calculate.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_paid',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_paid',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
