# Generated by Django 3.2.6 on 2021-08-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20210427_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='allowance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='allowance',
            field=models.FloatField(default=0.0),
        ),
    ]
