# Generated by Django 3.2.6 on 2021-08-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_auto_20210825_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, choices=[('', ''), ('Administration', 'Administration'), ('Article author', 'Article author'), ('Article cancellation fee', 'Article cancellation fee'), ('Consulting', 'Consulting'), ('Expenses', 'Expenses'), ('Editing', 'Editing'), ('Fact check', 'Fact check'), ('Photographs', 'Photographs'), ('Subediting', 'Subediting'), ('Sundry', 'Sundry')], default='Article author', max_length=100, verbose_name='secondary description'),
        ),
    ]
