# Generated by Django 3.2.15 on 2023-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_ratecard_bonus_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratecard',
            name='bonus_bonus',
        ),
        migrations.AlterField(
            model_name='ratecard',
            name='bonus',
            field=models.FloatField(default=500.0),
        ),
    ]
