# Generated by Django 4.2.5 on 2024-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20230310_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transport_claim',
            field=models.TextField(blank=True, help_text='Explain any transport claims  you would like to make. Email odometer photos or receipts to invoices@groundup.org.za.', max_length=3000),
        ),
    ]
