# Generated by Django 4.2.18 on 2025-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_invoice_transport_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='level_exceptional_plus',
            field=models.FloatField(default=2.65),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='level',
            field=models.CharField(choices=[('intern', 'Intern'), ('standard', 'Standard'), ('senior', 'Senior'), ('experienced', 'Experienced'), ('exceptional', 'Exceptional'), ('exceptional_plus', 'Exceptional Plus')], default='standard', max_length=20),
        ),
    ]
