# Generated by Django 5.2 on 2026-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0051_alter_author_unique_together_and_more'),
        ('payment', '0033_ratecard_level_exceptional_plus_alter_invoice_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('author', 'invoice_num'), name='unique_author_invoice_num'),
        ),
    ]
