# Generated by Django 5.2.13 on 2026-08-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0054_video_copyright_alter_video_credits_and_more'),
        ('payment', '0034_alter_invoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='newsroom.video'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, choices=[('', ''), ('Administration', 'Administration'), ('Article author', 'Article author'), ('Article cancellation fee', 'Article cancellation fee'), ('Consulting', 'Consulting'), ('Expenses', 'Expenses'), ('Editing', 'Editing'), ('Fact check', 'Fact check'), ('Photographs', 'Photographs'), ('Subediting', 'Subediting'), ('Sundry', 'Sundry'), ('Video contributor', 'Video contributor')], default='Article author', max_length=100, verbose_name='secondary description'),
        ),
    ]
