# Generated by Django 2.1.4 on 2018-12-10 16:18

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200)),
                ('suggested_caption', models.CharField(blank=True, max_length=600)),
                ('alt', models.CharField(blank=True, help_text='Description of image for assistive technology', max_length=600, verbose_name='short title')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('copyright', models.TextField(blank=True, help_text='Leave blank for default')),
                ('credit', models.TextField(blank=True, help_text='Leave blank for default')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('albums', models.ManyToManyField(blank=True, to='gallery.Album')),
                ('keywords', models.ManyToManyField(blank=True, to='gallery.Keyword')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author')),
            ],
            options={
                'ordering': ['-featured', '-modified'],
            },
        ),
        migrations.AddField(
            model_name='duplicate',
            name='photograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photograph'),
        ),
        migrations.AlterUniqueTogether(
            name='duplicate',
            unique_together={('photograph', 'image')},
        ),
    ]
