# Generated by Django 4.2.18 on 2025-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photograph_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='featured_on_front_page_from',
            field=models.DateTimeField(blank=True, help_text='Start date/time for featuring on front page', null=True),
        ),
        migrations.AddField(
            model_name='photograph',
            name='featured_on_front_page_to',
            field=models.DateTimeField(blank=True, help_text='End date/time for featuring on front page', null=True),
        ),
        migrations.AddField(
            model_name='photograph',
            name='include_short_title',
            field=models.BooleanField(default=False, help_text='Include short title when featured on front page'),
        ),
        migrations.AddField(
            model_name='photograph',
            name='include_suggested_caption',
            field=models.BooleanField(default=False, help_text='Include suggested caption when featured on front page'),
        ),
    ]
