# Generated by Django 4.2.29 on 2026-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photograph_featured_on_front_page_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='slider_position',
            field=models.CharField(choices=[('center', 'Middle (Default)'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right'), ('contain', 'Show Entire Image')], default='center', help_text='Which part of the image to show in the front page slider', max_length=20),
        ),
    ]
