# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160927_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='albums',
            field=models.ManyToManyField(blank=True, to='gallery.Album'),
        ),
    ]
