# Generated by Django 4.2.29 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photograph_slider_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='alt',
            field=models.CharField(blank=True, help_text='Keep short. Used for both assistive technology and as title in gallery', max_length=600, verbose_name='short title'),
        ),
    ]
