# Generated by Django 5.2 on 2026-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photograph_alt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duplicate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='duplicate',
            constraint=models.UniqueConstraint(fields=('photograph', 'image'), name='unique_photograph_image'),
        ),
    ]
