# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photograph_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['modified']},
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['-modified']},
        ),
    ]
