# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20161126_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='copyright',
            field=models.TextField(blank=True, help_text='Leave blank for default'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='credit',
            field=models.TextField(blank=True, help_text='Leave blank for default'),
        ),
    ]
