# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20161126_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='alt',
            field=models.CharField(blank=True, help_text='Description of image for assistive technology', max_length=600, verbose_name='short title'),
        ),
    ]
