# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20170208_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200)),
                ('processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photograph')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='duplicate',
            unique_together=set([('photograph', 'image')]),
        ),
    ]
