# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0014_auto_20160914_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
