# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0016_auto_20160914_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('our_reference', models.CharField(blank=True, max_length=200)),
                ('their_reference', models.CharField(blank=True, max_length=200)),
                ('sys_generated', models.BooleanField(default=False)),
                ('date_generated', models.DateTimeField(null=True)),
                ('date_approved', models.DateTimeField(null=True)),
                ('date_processed', models.DateTimeField(null=True)),
                ('date_rejected', models.DateTimeField(null=True)),
                ('date_notified_approved', models.DateTimeField(null=True)),
                ('date_notified_processed', models.DateTimeField(null=True)),
                ('invoice', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('proof', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('commission_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('tax_percent', models.DecimalField(decimal_places=0, default=25, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='notified_authors',
            new_name='commissions_processed',
        ),
        migrations.AddField(
            model_name='article',
            name='override_commissions_system',
            field=models.CharField(choices=[('NO', 'No'), ('PROCESS', 'Process commissions for this article'), ('NOPROCESS', "Don't process commissions for this article")], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='commission',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Article'),
        ),
        migrations.AddField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author'),
        ),
    ]
