# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0017_auto_20161024_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['author', 'article']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_notified_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_notified_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
