# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0021_auto_20161028_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='commission',
            name='funder',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='ledger',
        ),
        migrations.AddField(
            model_name='commission',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Fund'),
        ),
    ]
