# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0029_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
