# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0031_auto_20161104_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['author', 'article'], 'verbose_name': 'payment'},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='tax_percent',
        ),
        migrations.AddField(
            model_name='commission',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='amount'),
        ),
    ]
