# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0033_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Invoice'),
        ),
    ]
