# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0035_auto_20161105_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-status', '-modified']},
        ),
    ]
