# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0040_auto_20161106_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_notified_payment',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
