# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0041_invoice_date_notified_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
