# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0057_auto_20170929_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='external_primary_image',
            field=models.CharField(blank=True, help_text='If the primary image has a value, it overrides this.', max_length=500, verbose_name='primary image URL'),
        ),
    ]
