# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0063_auto_20180108_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='copyright',
            field=models.TextField(blank=True, default='&copy; 2018'),
        ),
    ]
