# Generated by Django 3.0.1 on 2020-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.CharField(max_length=81, unique=True)),
                ('solution', models.CharField(blank=True, max_length=81)),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('difficulty', models.CharField(choices=[('0', 'Unknown'), ('1', 'Simple'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Very hard')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
