# Generated by Django 3.0.1 on 2020-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Very hard'), ('5', 'Extremely hard'), ('6', 'Absurd')], default='0', max_length=1),
        ),
    ]
