# Generated by Django 3.0.1 on 2020-12-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_auto_20201201_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Very easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very hard'), ('6', 'Extremely hard')], default='0', max_length=1),
        ),
    ]
