# Generated by Django 2.1.4 on 2018-12-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byline', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('rejected', models.BooleanField(default=False)),
                ('note_to_writer', models.TextField(blank=True)),
                ('notified_letter_writer', models.BooleanField(default=False)),
                ('notified_editors', models.BooleanField(default=False)),
                ('replace_with_note', models.BooleanField(default=False, help_text='If checked, then the note to the writer completely overrides the standard response sent to writer.')),
                ('notes_for_editors', models.TextField(blank=True)),
                ('being_dealt_with', models.BooleanField(default=False)),
                ('css_classes', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('position', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.Article')),
            ],
            options={
                'verbose_name': 'letter',
                'ordering': ['article', 'position', 'published'],
                'verbose_name_plural': 'letters to the editor',
            },
        ),
    ]
