# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_auto_20160509_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='rejected_reason',
            new_name='note_to_writer',
        ),
    ]
