# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_auto_20180415_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='being_dealt_with',
            field=models.BooleanField(default=False),
        ),
    ]
