# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsroom', '0044_auto_20161107_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Article author', max_length=30)),
                ('sys_generated', models.BooleanField(default=False)),
                ('date_generated', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_notified_approved', models.DateTimeField(blank=True, null=True)),
                ('commission_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='amount')),
                ('taxable', models.BooleanField(default=True)),
                ('vatable', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Article')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author')),
            ],
            options={
                'ordering': ['author', 'article'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField(default=0)),
                ('identification', models.CharField(blank=True, help_text='SA ID, passport or some form of official identification', max_length=20)),
                ('dob', models.DateField(blank=True, help_text='Please fill this in. Required by SARS.', null=True, verbose_name='date of birth')),
                ('address', models.TextField(blank=True, help_text='Please fill this in. Required by SARS.')),
                ('bank_name', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_type', models.CharField(default='CURRENT', max_length=20)),
                ('bank_branch_name', models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20)),
                ('bank_branch_code', models.CharField(blank=True, help_text='Unnecessary for Capitec, FNB, Standard, Nedbank and Absa', max_length=20)),
                ('swift_code', models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=12)),
                ('iban', models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=34)),
                ('tax_no', models.CharField(blank=True, help_text='Necessary for SARS.', max_length=50, verbose_name='tax number')),
                ('tax_percent', models.DecimalField(decimal_places=0, default=25, help_text='Unless you have a tax directive we have to deduct 25% PAYE for SARS.', max_digits=2, verbose_name='tax %')),
                ('vat', models.DecimalField(decimal_places=0, default=0, help_text='If you are VAT regisered set this to 14 else leave at 0', max_digits=2, verbose_name='vat %')),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='amount')),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('vat_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('invoice', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('proof', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('0', 'Unpaid'), ('1', 'Queried by reporter-unpaid'), ('2', 'Approved by reporter-unpaid'), ('3', 'Approved by editor-unpaid'), ('4', 'Paid')], default='0', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('date_time_reporter_approved', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_time_editor_approved', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_time_processed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_notified_payment', models.DateTimeField(blank=True, editable=False, null=True)),
                ('our_reference', models.CharField(blank=True, max_length=20)),
                ('their_reference', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom.Author')),
            ],
            options={
                'ordering': ['status', '-modified'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Selecting a fund approves the commission', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Fund'),
        ),
        migrations.AddField(
            model_name='commission',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Invoice'),
        ),
    ]
