# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20161108_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=0, default=0, help_text='If you are VAT regisered set this to 14 else leave at 0', max_digits=2, verbose_name='VAT %'),
        ),
    ]
