# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20161109_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-', 'Invoice being prepared by editor'), ('0', 'Reporter needs to approve'), ('1', 'Queried by reporter'), ('2', 'Approved by reporter'), ('3', 'Approved by editor'), ('4', 'Paid')], default='-', max_length=2),
        ),
    ]
