# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_commission_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, default='Article author', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('-', 'Invoice being prepared by editor'), ('0', 'Reporter needs to approve'), ('1', 'Queried by reporter'), ('2', 'Approved by reporter'), ('3', 'Approved by editor'), ('4', 'Paid'), ('5', 'Deleted')], default='-', max_length=2),
        ),
    ]
