# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20170904_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Only relevant for banks outside SA', max_length=12),
        ),
    ]
