# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 10:21
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


def set_blank(apps, schema_editor):
    Invoice = apps.get_model('payment', 'Invoice')
    for invoice in Invoice.objects.all():
        if invoice.invoice is None:
            invoice.invoice = ""
        if invoice.proof is None:
            invoice.proof = ""
        invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20170904_1534'),
    ]

    operations = [
        migrations.RunPython(set_blank),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='proof',
            field=filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
