# Generated by Django 2.1.4 on 2019-01-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_question', models.CharField(max_length=200)),
                ('full_question', models.TextField(blank=True)),
                ('summary_answer', models.CharField(blank=True, max_length=200)),
                ('full_answer', models.TextField(blank=True)),
                ('original_question', models.TextField(blank=True)),
                ('answer_for_sender', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('sender_notified', models.BooleanField(default=False)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
