# Generated by Django 3.0.10 on 2021-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agony', '0003_qanda_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
