# Generated by Django 3.0.10 on 2021-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agony', '0004_qanda_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Agony aunt'),
        ),
    ]
