# Generated by Django 4.2.7 on 2024-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agony', '0005_auto_20210115_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='status',
            field=models.CharField(default='O', max_length=2),
        ),
    ]
