# Generated by Django 4.2.7 on 2024-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agony', '0006_qanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='status',
            field=models.CharField(choices=[('O', 'Old'), ('U', 'Unprocessed'), ('Q', 'Query'), ('I', 'Ignore'), ('R', 'Notify reader only'), ('P', 'Publish only'), ('B', 'Publish and notify reader')], default='O', max_length=2),
        ),
    ]
