# Generated by Django 4.2.18 on 2025-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agony', '0008_alter_qanda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='status',
            field=models.CharField(choices=[('O', 'Old'), ('U', 'Unprocessed'), ('Q', 'Query'), ('I', 'Ignore'), ('R', 'Notify reader only'), ('P', 'Publish only'), ('B', 'Publish and notify reader'), ('N', 'Unpublished')], default='U', max_length=2),
        ),
    ]
