# Generated by Django 4.2.27 on 2026-03-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('republisher', '0004_republisher_active'),
        ('licencing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencing.licence')),
                ('republisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='republisher.republisher')),
            ],
            options={
                'ordering': ['republisher'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FilePathField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencing.licensee')),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='licensee',
            constraint=models.UniqueConstraint(fields=('republisher', 'licence'), name='unique_licensee'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('licensee', 'document', 'date_from'), name='unique_contract'),
        ),
    ]
