# Generated by Django 4.2.27 on 2026-03-09 21:03

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('licencing', '0002_licensee_contract_licensee_unique_licensee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200),
        ),
    ]
