# Generated by Django 4.2.27 on 2026-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencing', '0003_alter_contract_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='summary',
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='licensee',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
