# Generated by Django 4.2.27 on 2026-03-11 15:43

import datetime
from django.db import migrations, models
import licencing.models


class Migration(migrations.Migration):

    dependencies = [
        ('licencing', '0004_remove_licence_summary_contract_notes_licensee_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(default=licencing.models.one_year_from_today),
        ),
    ]
