# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photograph_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photograph',
            old_name='album',
            new_name='albums',
        ),
    ]
