# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160927_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='photographs', to='gallery.Album'),
        ),
    ]
