# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160927_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='alt',
            field=models.CharField(blank=True, help_text='Description of image for assistive technology', max_length=600),
        ),
    ]
