# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20161104_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
