# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20161213_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['-featured', '-modified']},
        ),
    ]
