# Generated by Django 3.2.15 on 2023-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donor',
            name='registered_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
