# Generated by Django 3.2.15 on 2023-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0002_auto_20230413_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
