# Generated by Django 3.2.15 on 2023-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0003_donation_donation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_abr', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
