# Generated by Django 3.2.15 on 2023-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0006_auto_20230606_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
