# Generated by Django 3.2.15 on 2023-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0007_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_abr',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_url',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
